### Question:
Write a function to apply Min-Max Scaling to normalize a dataset. The function should scale the features between 0 and 1.

In [1]:
import numpy as np


In [2]:
def min_max_scaling(data):
    """
    Apply Min-Max Scaling to normalize the dataset.
    The function scales the features between 0 and 1.
    
    Parameters:
    - data: 2D numpy array or a list of lists representing the dataset
    
    Returns:
    - Scaled data as a 2D numpy array with values between 0 and 1
    """
    # Convert data to a numpy array if it's not already
    data = np.array(data)
    
    # Calculate the min and max of each column (feature)
    min_vals = np.min(data, axis=0)
    max_vals = np.max(data, axis=0)
    
    # Apply the Min-Max scaling formula
    scaled_data = (data - min_vals) / (max_vals - min_vals)
    
    return scaled_data


In [3]:
data = np.array([[2, 4, 6], 
                 [8, 10, 12], 
                 [3, 5, 7], 
                 [5, 7, 9]])

In [5]:
scaled_data = min_max_scaling(data)
print("Original Data:")
print(data)
print("\nScaled Data:")
print(scaled_data)

Original Data:
[[ 2  4  6]
 [ 8 10 12]
 [ 3  5  7]
 [ 5  7  9]]

Scaled Data:
[[0.         0.         0.        ]
 [1.         1.         1.        ]
 [0.16666667 0.16666667 0.16666667]
 [0.5        0.5        0.5       ]]
